spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: XiePeng2045
    url: jdbc:mysql://www.pongshy.com:3306/db1?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  aop:
    proxy-target-class: true
  jackson:
    time-zone: GMT+8


server:
  servlet:
    context-path: /api
  port: 8080



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.pongshy.assistant.model.entity
